### ISSUE TITLE
Doesn't work with (yet-to-be-released) Laravel 5.4

### ISSUE THREAD

**Issue by mstnorris** [laracasts/Laravel-5-Generators-Extended#117]
```
PHP Fatal error:  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found in /Users/Mike/Code/Laravel/moodeebee.com/vendor/laracasts/generators/src/Commands/MigrationMakeCommand.php on line 16

[Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found
```

I forked the repository and updated the namespace detector trait classname from **AppNamespaceDetectorTrait** to **DetectsApplicationNamespace** and although that surpasses the errors, the files that are generated don't have the correct class name.

**Comment by dansup** [comment]
Yeah this affected me when updating Laravel to 5.4 which is out now.

**Comment by fancenl** [comment]
Same here! :)

**Comment by joeldbirch** [comment]
This just bit me, too.

**Comment by Jaspur** [comment]
Yep, same here.

**Comment by jubasse** [comment]
It just needs to replace `Illuminate\Console\AppNamespaceDetectorTrait` by `Illuminate\Console\DetectsApplicationNamespace` wich provides the same function `getAppNamespace` on the command `Laracasts\Generators\Commands\MigrationMakeCommand` and before it works.

**Comment by uusa35** [comment]
any clues ?

**Comment by stedop** [comment]
Yeah so, looks like that trait has been removed from laravel,  I can understand why, it started a larger piece of code but by 5.3 was just this

```
<?php
namespace Illuminate\Console;
use Illuminate\Container\Container;
trait AppNamespaceDetectorTrait
{
    /**
     * Get the application namespace.
     *
     * @return string
     */
    protected function getAppNamespace()
    {
        return Container::getInstance()->getNamespace();
    }
}
```

I'm going to submit a pr to fix this shortly.

**Comment by stedop** [comment]
In facto I just checked the current prs and #120 will fix this using a newer way.

**Comment by rhonz10** [comment]
I tried to update src/Commands/MigrationMakeCommand.php with the fix from #120, migration file created but the class name is incorrect. 
```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class App\ extends Migration
{
```
instead of something like

```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePostTagPivotTable extends Migration
{
```

providing a correct class name migrates successfully.

**Comment by Jared87** [comment]
In my case replacing AppNamespaceDetectorTrait to DetectsApplicationNamespace on the following Lines worked.
src/Commands/MigrationMakeCommand.php:5
src/Commands/MigrationMakeCommand.php:16

**Comment by tabacitu** [comment]
Also fixed by #119 (already merged, needs tag).

**Comment by AbdelilahLbardi** [comment]
I am using Laracasts generators to generate migration files for my [package] and need to require the update that supports Laravel 5.4 .

Here's my composer.json schema:

````json
"require": {
    "laracasts/generators": "1.1.3"
},
````

**Cleared the composer cache and changed the release to `dev-master`** but i still have the same error. 

````bash
Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found in 

C:\Users\abdelila\Documents\auctions\vendor\laracasts\generators\src\Commands\MigrationMakeCommand.php on line 16
````

[package]: https://packagist.org/packages/abdelilahlbardi/laragenerator

**Comment by tabacitu** [comment]
@AbdelilahLbardi , try:
```
"require": {
        "laracasts/generators": "dev-master as 1.1.4",
},
```

Cheers!

**Comment by AbdelilahLbardi** [comment]
Hi @tabacitu, thanks for your answer.
I changed the version but still getting the same package trait error.

Regards,

**Comment by tabacitu** [comment]
@AbdelilahLbardi how about [this way](https://github.com/laracasts/Laravel-5-Generators-Extended/issues/124#issuecomment-277741259)?

**Comment by AbdelilahLbardi** [comment]
Too ! I already tried that one but it didn't work.

**Comment by Agapito78** [comment]
+1

**Comment by leanicoferreyra** [comment]
#AbdelilahLbardi donkey question, did you run "composer update" command after the composer.json change?

**Comment by AbdelilahLbardi** [comment]
@leanicoferreyra yes for sure. To make it working, the package users should require the laracasts generators too while waiting for the stable version to be released.

```` 
"require": {
    "laracasts/generators": "master@dev",
    "abdelilahlbardi/laragenerator": "^1.5"
} 
````

**Comment by leanicoferreyra** [comment]
With the exactly same problem i used this:
"require-dev": {
        "fzaninotto/faker": "~1.4",
        "laracasts/generators": "dev-master",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
This is a vanilla instalation  with generators
Then composer update and the register code in the provider...
And the problem was solved automaticaly.
Try with a fresh install to see if the problem have a solution like this and then try clean your current instalation. Without your fork maybe or other namespace possibly altered in the process.

**Comment by linares82** [comment]
I had the same problem, and found this code in laravel 5.3 
<?php
namespace Illuminate\Console;
use Illuminate\Container\Container;
trait AppNamespaceDetectorTrait
{
    /**
     * Get the application namespace.
     *
     * @return string
     */
    protected function getAppNamespace()
    {
        return Container::getInstance()->getNamespace();
    }
}

So I decided create the file in Illuminate\Console directly in laravel 5.4 inside vendor\laravel\framework\src\Illuminate\Console it is not correct but it works.

**Comment by ron-maxweb** [comment]
This works fine for me using `dev-master` as the version when upgrading from Laravel 5.3 to 5.4.

**Comment by DevAbas** [comment]
I changed this codes in the composer.json and fixed all issue
"require": {
        "laracasts/generators": "dev-master as 1.1.4"
}, 
Thanks everyone.

**Comment by mbarwick83** [comment]
"laracasts/generators": "dev-master" worked for me.

**Comment by arahmdiamola** [comment]
app.php

'env' => env('APP_ENV', 'development'),


and 

AppServiceProvider.php

if ($this->app->environment() == 'development') {
      $this->app->register('Laracasts\Generators\GeneratorsServiceProvider');
 }

**Comment by vlakoff** [comment]
Saving a step when [installing Backpack](https://laravel-backpack.readme.io/docs/install-on-laravel-54) wouldn't be a luxury. The code is ready and awaiting for 3 months, all you have to do now is to tag a release. Please.

**Comment by StephanMeijer** [comment]
Go fix this!

**Comment by Braunson** [comment]
Bump, any fix on this @laracasts @JeffreyWay ?

**Comment by perskinet** [comment]
Problem affects me too :) 

This is fixing partially:

"require": {
"laracasts/generators": "dev-master as 1.1.4"
},

When you generate migration for pivot you have no class name at generatet migration :) But artisan works :)

**Comment by hashlash** [comment]
i'm having issue for migration class name using `dev-master` version. The generated class name is always App\ which is give me error 

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '{'

when I try to do `php artisan migrate:refresh`

**Comment by Braunson** [comment]
@hashlash You have an error in your code. Look at the full stack error message for the file the error occurred in and fix the extra `{`

**Comment by mikeerickson** [comment]
So we are within a month of the release of Laravel 5.5 and this subject is still active.  
Seems as though this project is going the way of deprecation if you ask me.

**Comment by hashlash** [comment]
@Braunson i simply do the `php artisan migrate:refresh` and just get that two line of error info

By the way, the class name issue has been disscussed in [here](https://github.com/laracasts/Laravel-5-Generators-Extended/issues/63) and solved by [this merge](https://github.com/laracasts/Laravel-5-Generators-Extended/pull/53).

Can we combine the solutions for both problems (`AppNamespaceDetectorTrait not found` and `class name problem`)? I still newbie in this kind of thing

**Comment by tmaly1980** [comment]
@JeffreyWay , any suggestion what we should do?

**Comment by tabacitu** [comment]
Hi guys,

Jeffrey has been kind enough to give me write access to the repository, so:
- I've fixed and tagged the release, you can now use it after a ```composer update```;
- I'll do my best from now on to keep this reasonably up-to-date, but please keep in mind I have [12 other repositories in Backpack](https://github.com/Laravel-Backpack) that are my priority, so I can't dedicate a lot of time to this; any help is truly appreciated;

Cheers!
